services:
  postgres:
    image: 'postgres:latest'
    container_name: event-manager-core-db
    environment:
      - 'POSTGRES_DB=event_manager_db'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5433:5432'
#после будет подключение elastic stack, kafka, и чего то еще